# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 l5y

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: embedded-hal
        versions: [">=1.0.0"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
