# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 l5y

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
